# Generated by Django 4.2.2 on 2023-07-05 05:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Hindi', 'Hindi')], default='English', max_length=255),
        ),
    ]
